// c:\Kiran\Work\GIS\DATAVIZ\GeoInterpreter\scripts\orchestration\state_manager.js
class StateManager {
  constructor() {
    this._state = {
      layers: [], // Array of objects, each representing a data layer
      mapViewport: {}, // Object containing map's current center, zoom, rotation
      conversationHistory: [], // Array of message objects (user, assistant, tool)
      agentStatus: "initializing", // e.g., initializing, idle, planning, thinking, executing_tool, error
      activePlan: null, // Object storing the multi-step plan generated by AI Core
      currentLocation: null, // Stores the user's last geocoded location {latitude, longitude}
    };
    this._subscribers = new Set();
  }

  /**
   * Returns a deep copy of the current state.
   * @returns {object} The current application state.
   */
  getState() {
    return JSON.parse(JSON.stringify(this._state));
  }

  /**
   * Updates the state with new values and notifies all subscribers.
   * Only properties present in newState will be updated.
   * @param {object} newState - An object containing partial state updates.
   */
  updateState(newState) {
    let changed = false;
    for (const key in newState) {
      if (Object.prototype.hasOwnProperty.call(this._state, key)) {
        // Simple deep comparison for objects/arrays, otherwise direct comparison
        if (typeof newState[key] === 'object' && newState[key] !== null) {
          if (JSON.stringify(this._state[key]) !== JSON.stringify(newState[key])) {
            this._state[key] = JSON.parse(JSON.stringify(newState[key])); // Deep copy
            changed = true;
          }
        } else if (this._state[key] !== newState[key]) {
          this._state[key] = newState[key];
          changed = true;
        }
      }
    }

    if (changed) {
      this._notifySubscribers();
    }
  }

  /**
   * Subscribes a callback function to state changes.
   * @param {function} callback - The function to call when state changes.
   */
  subscribe(callback) {
    this._subscribers.add(callback);
  }

  /**
   * Unsubscribes a callback function from state changes.
   * @param {function} callback - The function to remove.
   */
  unsubscribe(callback) {
    this._subscribers.delete(callback);
  }

  /**
   * Notifies all subscribed callbacks about the state change.
   * @private
   */
  _notifySubscribers() {
    const currentState = this.getState(); // Pass a copy to prevent external modification
    this._subscribers.forEach(callback => {
      try {
        callback(currentState);
      } catch (error) {
        console.error("StateManager: Error notifying subscriber:", error);
      }
    });
  }

  /**
   * Resets the state to its initial values.
   */
  reset() {
    this._state = {
      layers: [],
      mapViewport: {},
      conversationHistory: [],
      agentStatus: "idle",
      activePlan: null,
    };
    this._notifySubscribers();
  }
}

export default StateManager;
